export default {
  login: 'jonytalukdar',
  id: 73661011,
  node_id: 'MDQ6VXNlcjczNjYxMDEx',
  avatar_url: 'https://avatars.githubusercontent.com/u/73661011?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/jonytalukdar',
  html_url: 'https://github.com/jonytalukdar',
  followers_url: 'https://api.github.com/users/jonytalukdar/followers',
  following_url:
    'https://api.github.com/users/jonytalukdar/following{/other_user}',
  gists_url: 'https://api.github.com/users/jonytalukdar/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/jonytalukdar/starred{/owner}{/repo}',
  subscriptions_url: 'https://api.github.com/users/jonytalukdar/subscriptions',
  organizations_url: 'https://api.github.com/users/jonytalukdar/orgs',
  repos_url: 'https://api.github.com/users/jonytalukdar/repos',
  events_url: 'https://api.github.com/users/jonytalukdar/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/jonytalukdar/received_events',
  type: 'User',
  site_admin: false,
  name: 'joney12',
  company: null,
  blog: '',
  location: null,
  email: null,
  hireable: null,
  bio: null,
  twitter_username: null,
  public_repos: 82,
  public_gists: 0,
  followers: 2,
  following: 4,
  created_at: '2020-10-29T16:55:32Z',
  updated_at: '2021-08-05T12:33:31Z',
};
